// The citizen-facing surface speaks the languages of the OneAquaHealth pilot sites: Greek for the
// Cretan streams, Italian for Benevento, English as the fallback. Clinician-facing pages and the
// alert text generated by the API stay in English (see docs/ARCHITECTURE.md).
//
// Kept deliberately small: a flat dictionary and a lookup, no routing segments and no dependency.

export type Locale = "en" | "el" | "it";

export const LOCALES: Locale[] = ["en", "el", "it"];
export const LOCALE_STORAGE_KEY = "locale";

export const LOCALE_NAMES: Record<Locale, string> = {
  en: "English",
  el: "Ελληνικά",
  it: "Italiano",
};

/** Short label for the header toggle. */
export const LOCALE_SHORT: Record<Locale, string> = { en: "EN", el: "ΕΛ", it: "IT" };

const en = {
  "nav.map": "Map",
  "nav.report": "Report",
  "nav.clinic": "Clinic",
  "nav.trends": "Trends",
  "map.seeTrends": "See what the reports add up to over four weeks",
  "nav.standards": "Standards",
  "nav.main": "Main",
  "nav.language": "Language",
  "nav.demoData": "Demo data",

  "report.title": "Report a stream observation",
  "report.intro": "Pick a site, say what you saw, and send. It takes less than a minute and helps warn nearby clinics early.",
  "report.site": "Site",
  "report.chooseSite": "Choose a site",
  "report.nearest": "Nearest to me",
  "report.nearestFound": "Nearest site: {site}, {km} km away.",
  "report.noGeolocation": "Location is not available in this browser.",
  "report.noSites": "No sites to choose from yet.",
  "report.permissionDenied": "Location permission was denied. Pick a site from the list.",
  "report.locateFailed": "Could not find your location. Pick a site from the list.",
  "report.observed": "What did you observe?",
  "report.seenByEye": "Seen by eye",
  "report.measuredIn": "Measured in {unit}",
  "report.measured": "Measured",
  "report.howMuch": "How much {indicator}?",
  "report.between": "Between {min} and {max}{unit}.",
  "report.yourName": "Your name",
  "report.nameHint": "Shown with your report and remembered on this device.",
  "report.note": "Note",
  "report.optional": "(optional)",
  "report.notePlaceholder": "Smell, colour, dead fish, anything unusual",
  "report.send": "Send report",
  "report.sending": "Sending…",
  "report.notSent": "Report not sent",
  "report.another": "Report another",
  "report.loading": "Loading report form",

  "report.errorSite": "Choose a site.",
  "report.errorIndicator": "Choose what you observed.",
  "report.errorNumber": "Enter a number for {indicator}.",
  "report.errorRange": "{indicator} must be between {min} and {max}{unit}.",
  "report.errorPresence": "Choose whether {indicator} is absent, present or abundant.",
  "report.errorName": "Enter your name so others know who reported this.",
  "report.errorGeneric": "Something went wrong. Try again.",
  "report.errorNoStore": "You appear to be offline, and this browser cannot store the report for later. Try again when you are back online.",

  "report.queuedSent": "Queued report sent",
  "report.queuedWaiting": "Queued, will send when online",
  "report.queuedSentBody": "Your {indicator} report for {site} has reached the server. See the banner above for its FHIR record.",
  "report.queuedWaitingBody": "Your {indicator} report for {site} is saved on this device. It will be sent automatically when you are back online, as long as this app is open.",

  "report.saved": "Report saved",
  "report.thanks": "Thank you, {name}. Your observation is now a standard FHIR resource.",
  "report.observedAt": "Observed",
  "report.photo": "Photo",
  "report.fhir": "FHIR",
  "report.raisedOne": "This report raised an alert",
  "report.raisedMany": "This report raised {count} alerts",
  "report.notified": "Clinics serving this site have been notified.",
  "report.seeOnMap": "See site on the map",
  "report.photoAlt": "Photo attached to this report",
  "photo.preparing": "Preparing photo…",
  "photo.previewAlt": "Preview of the photo attached to this report",
  "photo.noPeople": "Please don't photograph people. Photos are public with your report.",
  "photo.addFailed": "This photo could not be added.",

  "photo.label": "Photo",
  "photo.add": "Add a photo",
  "photo.remove": "Remove photo",
  "photo.hint": "Optional. Shrunk on your device before sending.",
  "photo.tooLarge": "That image is too large to send. Try a smaller photo.",
  "photo.failed": "Could not read that image. Try another one.",
  "photo.alt": "The photo you selected",

  "presence.absent": "Absent",
  "presence.present": "Present",
  "presence.abundant": "Abundant",

  "indicator.waterTemperature": "Water temperature",
  "indicator.pH": "pH",
  "indicator.dissolvedO2": "Dissolved O2",
  "indicator.conductivity": "Conductivity",
  "indicator.foam": "Foam/colour/smell",
  "indicator.filamentousAlgae": "Filamentous algae",
  "indicator.diptera": "Diptera",

  "map.title": "Stream sites",
  "map.intro": "Citizen observations from OneAquaHealth sites. Pick a site on the map or in the list to see its readings and alerts.",
  "map.allSites": "All sites",
  "map.byRisk": "Sites by risk",

  "footer.builtFor": "Built for the OneAquaHealth IEEE Global Hackathon.",
} satisfies Record<string, string>;

export type MessageKey = keyof typeof en;

const el: Partial<Record<MessageKey, string>> = {
  "nav.map": "Χάρτης",
  "nav.report": "Αναφορά",
  "nav.clinic": "Κλινική",
  "nav.trends": "Τάσεις",
  "map.seeTrends": "Δείτε τι δείχνουν οι αναφορές σε τέσσερις εβδομάδες",
  "nav.standards": "Πρότυπα",
  "nav.main": "Κύριο μενού",
  "nav.language": "Γλώσσα",
  "nav.demoData": "Δοκιμαστικά δεδομένα",

  "report.title": "Αναφέρετε μια παρατήρηση στο ρέμα",
  "report.intro": "Επιλέξτε σημείο, πείτε τι είδατε και στείλτε το. Παίρνει λιγότερο από ένα λεπτό και βοηθά να ειδοποιηθούν έγκαιρα οι κοντινές κλινικές.",
  "report.site": "Σημείο",
  "report.chooseSite": "Επιλέξτε σημείο",
  "report.nearest": "Το πλησιέστερο σε εμένα",
  "report.nearestFound": "Πλησιέστερο σημείο: {site}, σε απόσταση {km} χλμ.",
  "report.noGeolocation": "Η τοποθεσία δεν είναι διαθέσιμη σε αυτό το πρόγραμμα περιήγησης.",
  "report.noSites": "Δεν υπάρχουν ακόμη σημεία για επιλογή.",
  "report.permissionDenied": "Δεν δόθηκε άδεια τοποθεσίας. Επιλέξτε σημείο από τη λίστα.",
  "report.locateFailed": "Δεν ήταν δυνατή η εύρεση της τοποθεσίας σας. Επιλέξτε σημείο από τη λίστα.",
  "report.observed": "Τι παρατηρήσατε;",
  "report.seenByEye": "Με γυμνό μάτι",
  "report.measuredIn": "Μέτρηση σε {unit}",
  "report.measured": "Μέτρηση",
  "report.howMuch": "Ποσότητα — {indicator};",
  "report.between": "Μεταξύ {min} και {max}{unit}.",
  "report.yourName": "Το όνομά σας",
  "report.nameHint": "Εμφανίζεται μαζί με την αναφορά σας και αποθηκεύεται σε αυτή τη συσκευή.",
  "report.note": "Σημείωση",
  "report.optional": "(προαιρετικό)",
  "report.notePlaceholder": "Οσμή, χρώμα, νεκρά ψάρια, οτιδήποτε ασυνήθιστο",
  "report.send": "Αποστολή αναφοράς",
  "report.sending": "Αποστολή…",
  "report.notSent": "Η αναφορά δεν στάλθηκε",
  "report.another": "Νέα αναφορά",
  "report.loading": "Φόρτωση φόρμας αναφοράς",

  "report.errorSite": "Επιλέξτε σημείο.",
  "report.errorIndicator": "Επιλέξτε τι παρατηρήσατε.",
  "report.errorNumber": "Εισαγάγετε αριθμό για: {indicator}.",
  "report.errorRange": "Τιμή για {indicator}: μεταξύ {min} και {max}{unit}.",
  "report.errorPresence": "Επιλέξτε ποσότητα για: {indicator}.",
  "report.errorName": "Γράψτε το όνομά σας ώστε να φαίνεται ποιος έκανε την αναφορά.",
  "report.errorGeneric": "Κάτι πήγε στραβά. Δοκιμάστε ξανά.",
  "report.errorNoStore": "Φαίνεται ότι είστε εκτός σύνδεσης και αυτό το πρόγραμμα περιήγησης δεν μπορεί να αποθηκεύσει την αναφορά. Δοκιμάστε ξανά όταν συνδεθείτε.",

  "report.queuedSent": "Η αναφορά σε αναμονή στάλθηκε",
  "report.queuedWaiting": "Σε αναμονή, θα σταλεί με σύνδεση",
  "report.queuedSentBody": "Η αναφορά σας ({indicator}) για {site} έφτασε στον διακομιστή. Δείτε παραπάνω την εγγραφή FHIR.",
  "report.queuedWaitingBody": "Η αναφορά σας ({indicator}) για {site} αποθηκεύτηκε σε αυτή τη συσκευή. Θα σταλεί αυτόματα μόλις επανέλθει η σύνδεση, εφόσον η εφαρμογή είναι ανοιχτή.",

  "report.saved": "Η αναφορά αποθηκεύτηκε",
  "report.thanks": "Ευχαριστούμε, {name}. Η παρατήρησή σας είναι πλέον ένας τυποποιημένος πόρος FHIR.",
  "report.observedAt": "Παρατηρήθηκε",
  "report.photo": "Φωτογραφία",
  "report.fhir": "FHIR",
  "report.raisedOne": "Αυτή η αναφορά δημιούργησε μία ειδοποίηση",
  "report.raisedMany": "Αυτή η αναφορά δημιούργησε {count} ειδοποιήσεις",
  "report.notified": "Οι κλινικές που εξυπηρετούν αυτό το σημείο ειδοποιήθηκαν.",
  "report.seeOnMap": "Δείτε το σημείο στον χάρτη",
  "report.photoAlt": "Φωτογραφία συνημμένη σε αυτή την αναφορά",
  "photo.preparing": "Προετοιμασία φωτογραφίας…",
  "photo.previewAlt": "Προεπισκόπηση της φωτογραφίας της αναφοράς",
  "photo.noPeople": "Παρακαλούμε μη φωτογραφίζετε ανθρώπους. Οι φωτογραφίες δημοσιεύονται μαζί με την αναφορά σας.",
  "photo.addFailed": "Δεν ήταν δυνατή η προσθήκη αυτής της φωτογραφίας.",

  "photo.label": "Φωτογραφία",
  "photo.add": "Προσθήκη φωτογραφίας",
  "photo.remove": "Αφαίρεση φωτογραφίας",
  "photo.hint": "Προαιρετικό. Σμικρύνεται στη συσκευή σας πριν την αποστολή.",
  "photo.tooLarge": "Η εικόνα είναι πολύ μεγάλη για αποστολή. Δοκιμάστε μικρότερη φωτογραφία.",
  "photo.failed": "Δεν ήταν δυνατή η ανάγνωση της εικόνας. Δοκιμάστε μια άλλη.",
  "photo.alt": "Η φωτογραφία που επιλέξατε",

  "presence.absent": "Απουσιάζει",
  "presence.present": "Υπάρχει",
  "presence.abundant": "Άφθονο",

  "indicator.waterTemperature": "Θερμοκρασία νερού",
  "indicator.dissolvedO2": "Διαλυμένο οξυγόνο",
  "indicator.conductivity": "Αγωγιμότητα",
  "indicator.foam": "Αφρός/χρώμα/οσμή",
  "indicator.filamentousAlgae": "Νηματοειδή φύκη",
  "indicator.diptera": "Δίπτερα (προνύμφες κουνουπιών)",

  "map.title": "Σημεία ρεμάτων",
  "map.intro": "Παρατηρήσεις πολιτών από σημεία του OneAquaHealth. Επιλέξτε σημείο στον χάρτη ή στη λίστα για μετρήσεις και ειδοποιήσεις.",
  "map.allSites": "Όλα τα σημεία",
  "map.byRisk": "Σημεία ανά κίνδυνο",

  "footer.builtFor": "Φτιάχτηκε για το OneAquaHealth IEEE Global Hackathon.",
};

const it: Partial<Record<MessageKey, string>> = {
  "nav.map": "Mappa",
  "nav.report": "Segnala",
  "nav.clinic": "Clinica",
  "nav.trends": "Tendenze",
  "map.seeTrends": "Guarda cosa mostrano le segnalazioni in quattro settimane",
  "nav.standards": "Standard",
  "nav.main": "Menu principale",
  "nav.language": "Lingua",
  "nav.demoData": "Dati dimostrativi",

  "report.title": "Segnala un'osservazione sul corso d'acqua",
  "report.intro": "Scegli un sito, racconta cosa hai visto e invia. Richiede meno di un minuto e aiuta ad avvisare per tempo le cliniche vicine.",
  "report.site": "Sito",
  "report.chooseSite": "Scegli un sito",
  "report.nearest": "Il più vicino a me",
  "report.nearestFound": "Sito più vicino: {site}, a {km} km.",
  "report.noGeolocation": "La posizione non è disponibile in questo browser.",
  "report.noSites": "Non ci sono ancora siti tra cui scegliere.",
  "report.permissionDenied": "Permesso di posizione negato. Scegli un sito dall'elenco.",
  "report.locateFailed": "Non è stato possibile trovare la tua posizione. Scegli un sito dall'elenco.",
  "report.observed": "Che cosa hai osservato?",
  "report.seenByEye": "Visto a occhio nudo",
  "report.measuredIn": "Misurato in {unit}",
  "report.measured": "Misurato",
  "report.howMuch": "Quantità — {indicator}?",
  "report.between": "Tra {min} e {max}{unit}.",
  "report.yourName": "Il tuo nome",
  "report.nameHint": "Mostrato insieme alla segnalazione e ricordato su questo dispositivo.",
  "report.note": "Nota",
  "report.optional": "(facoltativa)",
  "report.notePlaceholder": "Odore, colore, pesci morti, qualsiasi cosa insolita",
  "report.send": "Invia segnalazione",
  "report.sending": "Invio…",
  "report.notSent": "Segnalazione non inviata",
  "report.another": "Invia un'altra",
  "report.loading": "Caricamento del modulo",

  "report.errorSite": "Scegli un sito.",
  "report.errorIndicator": "Scegli che cosa hai osservato.",
  "report.errorNumber": "Inserisci un numero per {indicator}.",
  "report.errorRange": "Valore per {indicator}: tra {min} e {max}{unit}.",
  "report.errorPresence": "Scegli la quantità per: {indicator}.",
  "report.errorName": "Inserisci il tuo nome, così si sa chi ha segnalato.",
  "report.errorGeneric": "Qualcosa è andato storto. Riprova.",
  "report.errorNoStore": "Sembri offline e questo browser non può salvare la segnalazione per dopo. Riprova quando torni online.",

  "report.queuedSent": "Segnalazione in coda inviata",
  "report.queuedWaiting": "In coda, sarà inviata quando sei online",
  "report.queuedSentBody": "La tua segnalazione ({indicator}) per {site} è arrivata al server. Vedi sopra il relativo record FHIR.",
  "report.queuedWaitingBody": "La tua segnalazione ({indicator}) per {site} è salvata su questo dispositivo. Sarà inviata automaticamente quando torni online, se l'app resta aperta.",

  "report.saved": "Segnalazione salvata",
  "report.thanks": "Grazie, {name}. La tua osservazione è ora una risorsa FHIR standard.",
  "report.observedAt": "Osservato",
  "report.photo": "Foto",
  "report.fhir": "FHIR",
  "report.raisedOne": "Questa segnalazione ha generato un'allerta",
  "report.raisedMany": "Questa segnalazione ha generato {count} allerte",
  "report.notified": "Le cliniche che servono questo sito sono state avvisate.",
  "report.seeOnMap": "Vedi il sito sulla mappa",
  "report.photoAlt": "Foto allegata a questa segnalazione",
  "photo.preparing": "Preparazione della foto…",
  "photo.previewAlt": "Anteprima della foto allegata alla segnalazione",
  "photo.noPeople": "Per favore non fotografare persone. Le foto sono pubbliche insieme alla segnalazione.",
  "photo.addFailed": "Non è stato possibile aggiungere questa foto.",

  "photo.label": "Foto",
  "photo.add": "Aggiungi una foto",
  "photo.remove": "Rimuovi la foto",
  "photo.hint": "Facoltativa. Ridotta sul tuo dispositivo prima dell'invio.",
  "photo.tooLarge": "L'immagine è troppo grande per l'invio. Prova con una foto più piccola.",
  "photo.failed": "Non è stato possibile leggere l'immagine. Provane un'altra.",
  "photo.alt": "La foto che hai scelto",

  "presence.absent": "Assente",
  "presence.present": "Presente",
  "presence.abundant": "Abbondante",

  "indicator.waterTemperature": "Temperatura dell'acqua",
  "indicator.dissolvedO2": "Ossigeno disciolto",
  "indicator.conductivity": "Conducibilità",
  "indicator.foam": "Schiuma/colore/odore",
  "indicator.filamentousAlgae": "Alghe filamentose",
  "indicator.diptera": "Ditteri (larve di zanzara)",

  "map.title": "Siti sui corsi d'acqua",
  "map.intro": "Osservazioni dei cittadini nei siti OneAquaHealth. Scegli un sito sulla mappa o nell'elenco per vedere letture e allerte.",
  "map.allSites": "Tutti i siti",
  "map.byRisk": "Siti per rischio",

  "footer.builtFor": "Realizzato per l'OneAquaHealth IEEE Global Hackathon.",
};

const MESSAGES: Record<Locale, Partial<Record<MessageKey, string>>> = { en, el, it };

export type Translate = (key: MessageKey, vars?: Record<string, string | number>) => string;

/** Missing translations fall back to English; an unknown key comes back as itself. */
export function translator(locale: Locale): Translate {
  return (key, vars) => {
    const template = MESSAGES[locale][key] ?? en[key] ?? key;
    if (!vars) return template;
    return template.replace(/\{(\w+)\}/g, (match, name: string) => String(vars[name] ?? match));
  };
}

export function isLocale(value: unknown): value is Locale {
  return typeof value === "string" && (LOCALES as string[]).includes(value);
}

export function readLocale(): Locale {
  try {
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
    if (isLocale(stored)) return stored;
    // First visit: follow the browser, so a Greek phone opens in Greek.
    const preferred = navigator.languages?.map((tag) => tag.split("-")[0]).find(isLocale);
    return preferred ?? "en";
  } catch {
    return "en";
  }
}

export function applyLocale(locale: Locale): void {
  document.documentElement.setAttribute("lang", locale);
}

// Mirrors readLocale/applyLocale, inlined in the document head so <html lang> is right before paint.
export const LOCALE_SCRIPT = `(function(){try{var l=["en","el","it"];var s=localStorage.getItem(${JSON.stringify(LOCALE_STORAGE_KEY)});if(l.indexOf(s)<0){s=(navigator.languages||[navigator.language||"en"]).map(function(t){return String(t).split("-")[0]}).filter(function(t){return l.indexOf(t)>=0})[0]||"en"}document.documentElement.setAttribute("lang",s)}catch(e){}})()`;
