// Writes sample FHIR resources produced by the API's real mapping code to samples/generated/.
// Every citizen indicator gets at least one sample, so new indicators are covered automatically.
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { toOahObservation } from "../api/src/mapping.js";
import { CITIZEN_INDICATORS, type CitizenIndicator } from "../api/src/oah.js";

const outDir = join(dirname(fileURLToPath(import.meta.url)), "samples", "generated");
const SITE_ID = "almyros-reach"; // matches samples/baseline/Location-almyros-reach.json

// Plausible field values for quantity indicators. Indicators missing here fall back to a default.
const QUANTITY_VALUES: Record<string, number> = {
  waterTemperature: 27.5,
  pH: 7.8,
  dissolvedO2: 3.6,
  conductivity: 820,
};
const PRESENCE_VALUES = ["absent", "present", "abundant"] as const;

type IndicatorEntry = { display: string; unit?: string; kind?: "quantity" | "presence" };

function isQuantity(entry: IndicatorEntry): boolean {
  return entry.kind ? entry.kind === "quantity" : entry.unit !== undefined;
}

function samples(): Array<[string, fhir4.Resource]> {
  const out: Array<[string, fhir4.Resource]> = [];
  for (const [id, entry] of Object.entries(CITIZEN_INDICATORS) as Array<[CitizenIndicator, IndicatorEntry]>) {
    const values = isQuantity(entry) ? [QUANTITY_VALUES[id] ?? 1] : [...PRESENCE_VALUES];
    for (const value of values) {
      const observation = toOahObservation({
        siteId: SITE_ID,
        indicator: id,
        observedAt: "2026-07-14T09:30:00Z",
        reporter: "Validation sample",
        value: value as never,
        note: "Generated by validation/generate-samples.ts",
      });
      const name = typeof value === "number" ? id : `${id}-${value}`;
      const { resourceType, ...rest } = observation;
      out.push([`Observation-${name}`, { resourceType, id: `sample-${name}`.toLowerCase(), ...rest }]);
    }
  }
  // Add builders for other API-produced resources (seed Locations, alerts, ...) here as they land.
  return out;
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
const all = samples();
for (const [name, resource] of all) {
  writeFileSync(join(outDir, `${name}.json`), `${JSON.stringify(resource, null, 2)}\n`);
}
console.log(`Wrote ${all.length} samples to ${outDir}`);
