// Writes sample FHIR resources produced by the API's real code to samples/generated/:
// citizen report mappings for every indicator and value kind, the seed data, and alert resources.
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { toCommunication, toDetectedIssue } from "../api/src/alerts.js";
import { toOahObservation } from "../api/src/mapping.js";
import { CITIZEN_INDICATORS, PRESENCE_VALUES, type CitizenIndicator } from "../api/src/oah.js";
import type { RiskDecision } from "../api/src/rules.js";
import { SITES, seedBundle } from "../api/src/seed.js";

const outDir = join(dirname(fileURLToPath(import.meta.url)), "samples", "generated");
const NOW = new Date("2026-07-15T12:00:00Z"); // fixed, so samples are reproducible
const SITE = SITES[0];

// One Observation per quantity indicator (mid-range value) and per presence value.
function citizenReports(): fhir4.Resource[] {
  return (Object.keys(CITIZEN_INDICATORS) as CitizenIndicator[]).flatMap((indicator) => {
    const entry = CITIZEN_INDICATORS[indicator];
    const values = entry.kind === "quantity" ? [(entry.min + entry.max) / 2] : [...PRESENCE_VALUES];
    return values.map((value) => ({
      ...toOahObservation({
        siteId: SITE.id,
        indicator,
        value,
        observedAt: "2026-07-14T09:30:00Z",
        reporter: "Validation sample",
        note: "Generated by validation/generate-samples.ts",
      }),
      id: `report-${indicator}${typeof value === "string" ? `-${value}` : ""}`,
    }));
  });
}

// Every seed resource, except that the synthetic citizen history (same mapping as above, ~200
// Observations) is cut down to one Observation per indicator.
function seedResources(): fhir4.Resource[] {
  const resources = (seedBundle(NOW).entry ?? []).flatMap((e) => (e.resource ? [e.resource] : []));
  const seenHistory = new Set<string>();
  return resources.filter((r) => {
    if (r.resourceType !== "Observation" || !r.id?.startsWith("seed-")) return true;
    const code = (r as fhir4.Observation).code.coding?.[0]?.code ?? "";
    if (seenHistory.has(code)) return false;
    seenHistory.add(code);
    return true;
  });
}

// A raised algal-bloom alert: the DetectedIssue and the Communication sent to one clinic.
function alertResources(): fhir4.Resource[] {
  const site = { id: SITE.id, name: SITE.name, waterBody: "Almyros Stream", region: SITE.region, lat: SITE.lat, lon: SITE.lon };
  const decision: RiskDecision = {
    risk: "algal-bloom",
    fired: true,
    level: "high",
    conditions: [
      { text: "Filamentous algae reported as abundant.", met: true, evidence: ["report-filamentousAlgae-abundant"] },
      { text: "Water temperature 27.5 °C (threshold 25 °C).", met: true, evidence: ["report-waterTemperature"] },
      { text: "0.4 mm rain in the last 7 days (Open-Meteo).", met: true, evidence: [] },
    ],
  };
  const issue = { ...toDetectedIssue(site, decision, NOW.toISOString()), id: "alert-algal-bloom" };
  const clinic = { id: "clinic-almyros", name: "Almyros Primary Care Unit (demo)" };
  const communication = { ...toCommunication(site, decision, `DetectedIssue/${issue.id}`, clinic), id: "alert-algal-bloom-clinic-almyros" };
  return [issue, communication];
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
const all = [...citizenReports(), ...seedResources(), ...alertResources()];
for (const resource of all) {
  // resourceType first, then id, for readable files.
  const { resourceType, id, ...rest } = resource;
  writeFileSync(join(outDir, `${resourceType}-${id}.json`), `${JSON.stringify({ resourceType, id, ...rest }, null, 2)}\n`);
}
console.log(`Wrote ${all.length} samples to ${outDir}`);
